language: node_js
addons:
  chrome: stable
node_js:
  - node
sudo: required
install:
  - npm install
script:
  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
