language: node_js
addons:
  chrome: stable
node_js:
  - node
sudo: required
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
  - npm install
script:
  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
